Book.insertMany([
    { title: 'Đắc nhân tâm', author: 'Dale Carnegie', status: 'Còn trống' },
    {
        title: 'Nhà giả kim',
        author: 'Paulo Coelho',
        status: 'Đã có người thuê',
    },
    {
        title: 'Harry Potter và Hòn đá Phù thủy',
        author: 'J.K. Rowling',
        status: 'Còn trống',
    },
    {
        title: 'Cuộc sống bí mật của Walter Mitty',
        author: 'James Thurber',
        status: 'Còn trống',
    },
    {
        title: 'Lược sử thời gian',
        author: 'Stephen Hawking',
        status: 'Đã có người thuê',
    },
    {
        title: 'Trăm năm cô đơn',
        author: 'Gabriel García Márquez',
        status: 'Còn trống',
    },
    {
        title: 'Chiến tranh và hòa bình',
        author: 'Leo Tolstoy',
        status: 'Còn trống',
    },
    { title: 'Bố già', author: 'Mario Puzo', status: 'Đã có người thuê' },
    { title: 'Kẻ sát nhân mù', author: 'Margaret Atwood', status: 'Còn trống' },
    { title: 'Đồi gió hú', author: 'Emily Brontë', status: 'Còn trống' },
    {
        title: 'Phía đông vườn địa đàng',
        author: 'John Steinbeck',
        status: 'Đã có người thuê',
    },
    { title: 'Mật mã Da Vinci', author: 'Dan Brown', status: 'Còn trống' },
    {
        title: 'Chuyện người tù',
        author: 'Aleksandr Solzhenitsyn',
        status: 'Còn trống',
    },
    {
        title: 'Anh em nhà Karamazov',
        author: 'Fyodor Dostoevsky',
        status: 'Còn trống',
    },
    {
        title: 'Tội ác và hình phạt',
        author: 'Fyodor Dostoevsky',
        status: 'Đã có người thuê',
    },
    {
        title: 'Chúa tể của những chiếc nhẫn',
        author: 'J.R.R. Tolkien',
        status: 'Còn trống',
    },
    {
        title: 'Người tình Sputnik',
        author: 'Haruki Murakami',
        status: 'Đã có người thuê',
    },
    {
        title: 'Bắt trẻ đồng xanh',
        author: 'J.D. Salinger',
        status: 'Còn trống',
    },
    {
        title: 'Hoàng tử bé',
        author: 'Antoine de Saint-Exupéry',
        status: 'Còn trống',
    },
    {
        title: 'Mặt trời cũng mọc',
        author: 'Ernest Hemingway',
        status: 'Đã có người thuê',
    },
    { title: 'Kẻ xa lạ', author: 'Albert Camus', status: 'Còn trống' },
    { title: 'Đồi thỏ', author: 'Richard Adams', status: 'Còn trống' },
    {
        title: 'Chuyện dài bất tận',
        author: 'Michael Ende',
        status: 'Đã có người thuê',
    },
    {
        title: 'Nghệ thuật yêu đương',
        author: 'Erich Fromm',
        status: 'Còn trống',
    },
    {
        title: 'Cái chết của Ivan Ilyich',
        author: 'Leo Tolstoy',
        status: 'Còn trống',
    },
    { title: 'Lolita', author: 'Vladimir Nabokov', status: 'Đã có người thuê' },
    { title: '1984', author: 'George Orwell', status: 'Còn trống' },
    {
        title: 'Thiên thần và ác quỷ',
        author: 'Dan Brown',
        status: 'Đã có người thuê',
    },
    {
        title: 'Tâm lý học đám đông',
        author: 'Gustave Le Bon',
        status: 'Còn trống',
    },
    { title: 'Sóng ngầm', author: 'Susanna Kaysen', status: 'Còn trống' },
    {
        title: 'Khế ước xã hội',
        author: 'Jean-Jacques Rousseau',
        status: 'Đã có người thuê',
    },
    {
        title: 'Sự thật về vụ án',
        author: 'Haruki Murakami',
        status: 'Còn trống',
    },
    { title: 'Căn phòng đỏ', author: 'August Strindberg', status: 'Còn trống' },
    {
        title: 'Tình yêu thời thổ tả',
        author: 'Gabriel García Márquez',
        status: 'Đã có người thuê',
    },
    {
        title: 'Những người khốn khổ',
        author: 'Victor Hugo',
        status: 'Còn trống',
    },
    { title: 'Người mẹ', author: 'Maxim Gorky', status: 'Còn trống' },
    {
        title: 'Moby-Dick',
        author: 'Hermaan Melville',
        status: 'Đã có người thuê',
    },
    {
        title: 'Cuốn theo chiều gió',
        author: 'Margaret Mitchell',
        status: 'Còn trống',
    },
    {
        title: 'Thế giới mới dũng cảm',
        author: 'Aldous Huxley',
        status: 'Còn trống',
    },
    {
        title: 'Cánh buồm đỏ thắm',
        author: 'Alexander Grin',
        status: 'Đã có người thuê',
    },
    { title: 'Tấm thảm', author: 'Terry Pratchett', status: 'Còn trống' },
    { title: 'Tình yêu và tội lỗi', author: 'Goethe', status: 'Còn trống' },
    {
        title: 'Đồi cỏ hoa',
        author: 'Peter S. Beagle',
        status: 'Đã có người thuê',
    },
    {
        title: 'Hội chợ phù hoa',
        author: 'William Makepeace Thackeray',
        status: 'Còn trống',
    },
    {
        title: 'Người đàn bà hoàn hảo',
        author: 'Oscar Wilde',
        status: 'Còn trống',
    },
    { title: 'Sóng vỗ', author: 'Virginia Woolf', status: 'Đã có người thuê' },
    {
        title: 'Mặt trời không bao giờ tắt',
        author: 'William Faulkner',
        status: 'Còn trống',
    },
    { title: 'Đỉnh gió hú', author: 'Emily Brontë', status: 'Còn trống' },
    {
        title: 'Bắt gọn',
        author: 'Raymond Chandler',
        status: 'Đã có người thuê',
    },
    {
        title: 'Sự trỗi dậy của loài người',
        author: 'H.G. Wells',
        status: 'Còn trống',
    },
    {
        title: 'Tâm lý học của tình yêu',
        author: 'Sigmund Freud',
        status: 'Còn trống',
    },
    {
        title: 'Tầm nhìn của Plato',
        author: 'Plato',
        status: 'Đã có người thuê',
    },
    { title: 'Chí Phèo', author: 'Nam Cao', status: 'Còn trống' },
    { title: 'Tuổi thơ dữ dội', author: 'Phùng Quán', status: 'Còn trống' },
    {
        title: 'Những cây cầu ở quận Madison',
        author: 'Robert James Waller',
        status: 'Đã có người thuê',
    },
    { title: 'Bố con cá gai', author: 'Lý Tử Hoa', status: 'Còn trống' },
    { title: 'Cuộc đời của Pi', author: 'Yann Martel', status: 'Còn trống' },
    { title: 'Lão Hạc', author: 'Nam Cao', status: 'Đã có người thuê' },
    { title: 'Không gia đình', author: 'Hector Malot', status: 'Còn trống' },
    {
        title: 'Những người đàn bà nhỏ bé',
        author: 'Louisa May Alcott',
        status: 'Còn trống',
    },
    {
        title: 'Đảo giấu vàng',
        author: 'Robert Louis Stevenson',
        status: 'Đã có người thuê',
    },
    { title: 'Đêm trắng', author: 'Fyodor Dostoevsky', status: 'Còn trống' },
    {
        title: 'Thép đã tôi thế đấy',
        author: 'Nikolai Ostrovsky',
        status: 'Còn trống',
    },
]);